apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.ConfigMap.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.ConfigMap.POSTGRES_USER }}
kind: ConfigMap
metadata:
  name: {{ printf "%s-db-configmap" .Release.Name | quote }}
  # doit matcher le configMapKeyRef.name de db.yaml
