apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-svc 
  labels:
    {{- include "fastapiapp.selectorLabels" . | nindent 4 }}
    component: database
spec:
  ports:
  - targetPort: 5432
    port: 5432
  selector:
    {{- include "fastapiapp.dbLabels" . | nindent 4 }}
