apiVersion: v1
data:
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | b64enc | quote }}
kind: Secret
metadata:
  name: {{ printf "%s-db-secret" .Release.Name | quote }}
  # doit matcher le secretKeyRef.name de db.yaml
