apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  movie-service-db
spec:
  selector:
    matchLabels:
      app: movie-db # has to match .spec.template.metadata.labels
  serviceName: movie-db
  template:
    metadata:
      labels:
        app: movie-db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: movie-postgres
        image: postgres:12.1-alpine
        ports:
          - containerPort: 5432
        env: 
          - name: POSTGRES_USER
            valueFrom: 
              configMapKeyRef:
                name: movie-db-config
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: movie-db-config
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: movie-db-secret
                key: POSTGRES_PASSWORD
        volumeMounts:
          - name: volume-movie-db
            mountPath: /var/lib/postgresql/data/
  volumeClaimTemplates:
    - metadata:
        name: volume-movie-db
      spec:
        accessModes: ["ReadWriteOnce"] 
        resources: 
          requests:
            storage: 1G



